apiVersion: v1
kind: Secret
metadata:
  name: ygt-services-event-svc
data:
  CLOUDINARY_CLOUD_NAME: {{ .Values.eventSvc.cloudinaryCloudName | b64enc }}
  CLOUDINARY_API_KEY: {{ .Values.eventSvc.cloudinaryApiKey | b64enc }}
  CLOUDINARY_API_SECRET: {{ .Values.eventSvc.cloudinaryApiSecret | b64enc }}
  DATABASE_URL: {{ .Values.databaseUrl | b64enc }}
