apiVersion: v1
kind: Service
metadata:
  name: event-service
spec:
  selector:
    app: event-svc
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30002
  type: NodePort
