apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: horbee/ygt-authentication
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: '5001'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ygt-services-authentication
                  key: JWT_SECRET
            - name: JWT_RT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ygt-services-authentication
                  key: JWT_RT_SECRET
            - name: RABBIT_MQ_PW
              valueFrom:
                secretKeyRef:
                  name: ygt-services-rabbitmq
                  key: rabbitmq-password
            # - name: MONGO_DB_PW
            #   valueFrom:
            #     secretKeyRef:
            #       name: ygt-services-mongodb
            #       key: mongodb-root-password
            - name: RABBIT_MQ_URI
              value: 'amqp://user1:$(RABBIT_MQ_PW)@ygt-services-rabbitmq-headless:5672'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ygt-services-authentication
                  key: DATABASE_URL
              # value: 'mongodb://root:$(MONGO_DB_PW)@ygt-services-mongodb-headless:27017/ygt-db?authSource=admin&directConnection=true'
            - name: ALLOWED_ORIGINS
              value: 'http://localhost:3000'
            - name: AZURE_CLIENT_ID
              value: 'test'
            - name: AZURE_TENANT_ID
              value: 'test'
