apiVersion: v1
kind: Secret
metadata:
  name: ygt-services-authentication
data:
  JWT_SECRET: {{ .Values.authentication.jwtSecret | b64enc }}
  JWT_RT_SECRET: {{ .Values.authentication.jwtRtSecret | b64enc }}
  DATABASE_URL: {{ .Values.databaseUrl | b64enc }}
