apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001
  type: NodePort